---
- name: Upgrade all packages (yum)
  ansible.builtin.yum:
    name: '*'
    state: latest
    exclude: "{{ exclude_packages }}"
    update_only: true
  when: ansible_pkg_mgr == "yum"
  register: patchingresult

- name: Combine results into single line
  ansible.builtin.set_fact:
    myresults: "{{ myresults | default([]) + [item[0] + ': ' + item[1]] }}"
  loop: "{{ patchingresult.changes.updated }}"
  loop_control:
    label: "{{ item[0] }}"
  when:
    - ansible_pkg_mgr == "yum"
    - patchingresult.changes.updated is defined

- name: Display Yum Patching Results
  ansible.builtin.debug:
    msg: "{{ myresults | default('System is up to date') }}"
  when:
    - ansible_pkg_mgr == "yum"

- name: Upgrade all packages (dnf)
  ansible.builtin.dnf:
    name: '*'
    state: latest
    exclude: "{{ exclude_packages }}"
    update_only: true
  when: ansible_pkg_mgr == "dnf"
  register: patchingresultdnf

- name: Display DNF Patching Results
  ansible.builtin.debug:
    msg: "{{ patchingresultdnf.results }}"
  when: ansible_pkg_mgr == "dnf"

- name: Ensure dnf-utils is installed
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  when: ansible_pkg_mgr == "dnf"

- name: Check to see if we need a reboot
  ansible.builtin.command: needs-restarting -r
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc > 1
  check_mode: false

- name: Reboot Server if Necessary
  ansible.builtin.reboot:
  when:
    - result.rc == 1
    - ansible_connection == "ssh"
